# Generated by Django 4.2.20 on 2025-04-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationplan',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='trip_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked')], default='planned', max_length=10),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='whos_going',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='planner.vacationplan')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('confirmation', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='planner.vacationplan')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.vacationplan')),
            ],
        ),
    ]
