# Generated by Django 4.2.20 on 2025-04-20 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0004_vacationplan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
