# Generated by Django 4.2.20 on 2025-05-09 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0006_vacationplan_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('invite_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='vacationplan',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='vacationplan',
            name='title',
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vacations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='trip_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='vacationplan',
            index=models.Index(fields=['start_date'], name='planner_vac_start_d_191377_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationplan',
            index=models.Index(fields=['end_date'], name='planner_vac_end_dat_38c2af_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationplan',
            index=models.Index(fields=['trip_type'], name='planner_vac_trip_ty_5d09dd_idx'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='vacation_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacations', to='planner.group'),
        ),
    ]
