# Generated by Django 5.2.1 on 2025-05-13 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_activity_suggested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
