# Generated by Django 5.2.1 on 2025-05-13 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_activity_voted_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='suggested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
