# Generated by Django 4.2.20 on 2025-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_activity_options_alter_activity_suggested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes for this activity'),
        ),
    ]
