# Generated by Django 4.2.20 on 2025-06-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_activity_notes'),
        ('planner', '0012_group_creator_group_description_and_more'),
    ]

    operations = [
    ]
