# Generated by Django 4.2.20 on 2025-06-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_merge_20250612_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='lodging_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('motel', 'Motel'), ('resort', 'Resort'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('house', 'House'), ('cabin', 'Cabin'), ('villa', 'Villa'), ('campground', 'Campground'), ('other', 'Other')], default='hotel', max_length=20),
        ),
    ]
