# Generated by Django 4.2.20 on 2025-06-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_lodging_lodging_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('ferry', 'Ferry'), ('car', 'Car'), ('other', 'Other')], default='flight', max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('confirmation', models.CharField(max_length=100)),
                ('departure_location', models.CharField(max_length=100)),
                ('arrival_location', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='planner.vacationplan')),
            ],
        ),
    ]
