# Generated by Django 4.2.20 on 2025-06-13 13:33

from django.db import migrations


def migrate_flights_to_transportation(apps, schema_editor):
    """Migrate existing Flight records to Transportation records"""
    Flight = apps.get_model('planner', 'Flight')
    Transportation = apps.get_model('planner', 'Transportation')
    
    for flight in Flight.objects.all():
        Transportation.objects.create(
            vacation=flight.vacation,
            transportation_type='flight',
            provider=flight.airline,
            confirmation=flight.confirmation,
            departure_location=flight.departure_airport,
            arrival_location=flight.arrival_airport,
            departure_time=flight.departure_time,
            arrival_time=flight.arrival_time,
            actual_cost=flight.actual_cost,
        )


def reverse_migrate_transportation_to_flights(apps, schema_editor):
    """Reverse migration: restore Flight records from Transportation records"""
    Flight = apps.get_model('planner', 'Flight')
    Transportation = apps.get_model('planner', 'Transportation')
    
    for transportation in Transportation.objects.filter(transportation_type='flight'):
        Flight.objects.create(
            vacation=transportation.vacation,
            airline=transportation.provider,
            confirmation=transportation.confirmation,
            departure_airport=transportation.departure_location,
            arrival_airport=transportation.arrival_location,
            departure_time=transportation.departure_time,
            arrival_time=transportation.arrival_time,
            actual_cost=transportation.actual_cost,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_add_transportation_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_flights_to_transportation,
            reverse_migrate_transportation_to_flights
        ),
    ]
