# Generated by Django 4.2.20 on 2025-06-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_migrate_flights_to_transportation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
