# Generated by Django 4.2.20 on 2025-06-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0017_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_vacation_invitations', models.BooleanField(default=True)),
                ('receive_activity_notifications', models.BooleanField(default=True)),
                ('receive_password_reset_emails', models.BooleanField(default=True)),
                ('receive_account_notifications', models.BooleanField(default=True)),
                ('receive_marketing_emails', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_email_valid', models.BooleanField(default=True)),
                ('bounce_count', models.IntegerField(default=0)),
                ('complaint_received', models.BooleanField(default=False)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('registration', 'Registration Confirmation'), ('password_reset', 'Password Reset'), ('vacation_invitation', 'Vacation Invitation'), ('activity_notification', 'Activity Notification'), ('unsubscribe_confirmation', 'Unsubscribe Confirmation'), ('marketing', 'Marketing Email'), ('system', 'System Notification')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('complained_at', models.DateTimeField(blank=True, null=True)),
                ('ses_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bounce_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bounce_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('complaint_feedback_type', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='planner_ema_status_33bd8e_idx'), models.Index(fields=['email_type'], name='planner_ema_email_t_2a8996_idx'), models.Index(fields=['recipient_email'], name='planner_ema_recipie_e88043_idx'), models.Index(fields=['ses_message_id'], name='planner_ema_ses_mes_bb623d_idx'), models.Index(fields=['created_at'], name='planner_ema_created_3abbbd_idx')],
            },
        ),
    ]
